#!/usr/bin/env bash
set -euo pipefail
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}" \
MODEL_VARIANT=challenger \
MUON_WEIGHT_DECAY="${MUON_WEIGHT_DECAY:-0.038}" \
USE_BIGRAM_HASH="${USE_BIGRAM_HASH:-0}" \
USE_SMEARGATE="${USE_SMEARGATE:-0}" \
SWA_ENABLED="${SWA_ENABLED:-0}" \
COMPILE_MODEL="${COMPILE_MODEL:-0}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-600}" \
ITERATIONS="${ITERATIONS:-2000}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}" \
EVAL_STRIDE="${EVAL_STRIDE:-0}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-100}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-1}" train_gpt.py 2>&1 | tee train.log
