#!/usr/bin/env bash
set -euo pipefail
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}" \
MODEL_VARIANT=frontier \
MUON_WEIGHT_DECAY="${MUON_WEIGHT_DECAY:-0.04}" \
ADAM_WEIGHT_DECAY="${ADAM_WEIGHT_DECAY:-0.01}" \
LOWBIT_STE="${LOWBIT_STE:-1}" \
USE_BIGRAM_HASH="${USE_BIGRAM_HASH:-1}" \
USE_SMEARGATE="${USE_SMEARGATE:-1}" \
SWA_ENABLED="${SWA_ENABLED:-1}" \
BIGRAM_BUCKETS="${BIGRAM_BUCKETS:-4096}" \
BIGRAM_DIM="${BIGRAM_DIM:-128}" \
ROPE_BASE="${ROPE_BASE:-50000}" \
SWA_EVERY="${SWA_EVERY:-50}" \
SWA_START_FRAC="${SWA_START_FRAC:-0.50}" \
EVAL_STRIDE="${EVAL_STRIDE:-256}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-600}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-8}" train_gpt.py 2>&1 | tee train.log
